### ISSUE TITLE
Not working on FF?

### ISSUE THREAD

**Issue by yochannah** [intermine/cross-intermine-search-tool#1]
No sites seem to load in firefox at all right now. example screenshot:

![image](https://user-images.githubusercontent.com/9271438/43770452-513d64f4-9a34-11e8-82e0-b0de1fd56a22.png)

Tell @amand1996 about this

**Comment by amanofb** [comment]
@yochannah ah, it was unexpected. I will check. :(

**Comment by amand1996** [comment]
It's a CORS issue. It will work when deployed on InterMine server. We can use a reverse proxy like [cors-anywhere](https://www.npmjs.com/package/cors-anywhere) to add cors headers. Another alternative is to update IM.js to support this. As far as I know, IM.js currenty doesn't have support for taking external headers. Not sure.

**Comment by yochannah** [comment]
adding a small note - I think this must be somehow related to imjs. I've just encountered the exact same issue in a different repo when I bundled imjs in. I'm glad we'd been through this problem before and figured it out! :)
