### ISSUE TITLE
Bugged Display

### ISSUE THREAD

**Issue by himanshukumar660** [intermine/cross-intermine-search-tool#4]
I have observed that the result entries for the individual mines are not aligned properly. The result entires must be padded for clean interface. The below picture presents the problem more clearly.
![screen shot 2018-08-14 at 5 45 48 pm](https://user-images.githubusercontent.com/16867533/44091368-dd9bb11a-9fea-11e8-8bd4-6846e337b10f.png)

**Comment by amand1996** [comment]
Fixed.

**Comment by yochannah** [comment]
@himanshukumar660 can you confirm this is fixed using http://cross-intermine-search-tool.herokuapp.com/#/ to test? (I won't be able to deploy the the .apps.intermine.org domain until tomorrow)

**Comment by himanshukumar660** [comment]
Yeah. I have checked it and it works fine.

**Comment by yochannah** [comment]
Thanks @himanshukumar660 for checking!
