### ISSUE TITLE
Error communicating with mines is too bright

### ISSUE THREAD

**Issue by yochannah** [intermine/cross-intermine-search-tool#8]
when a mine connection fails, the error text on the top is a very bright red. A light / inobtrusive colour would be better. 

![image](https://user-images.githubusercontent.com/9271438/47929366-ae0d6280-dec0-11e8-9964-5acb91bcdbcc.png)

**Comment by flaredragon** [comment]
Hi I've worked on this issue! Would like to get your feedback on PR.
